version: '3'

services:
  nginx:
    build: build/nginx
    image: testtask/nginx
    hostname: nginx
    volumes:
     - "./volumes/nginx/log/:/var/log/nginx/"
     - "./build/nginx/testtask.local.conf:/etc/nginx/conf.d/default.conf:ro"
     - "..:/testtask:ro"
    ports:
     - "127.0.0.1:80:80"
    networks:
     - testtask_swarm
    depends_on:
     - fpm

  fpm:
    build: build/php-fpm
    image: testtask/php-fpm
    hostname: fpm
    volumes:
     - "..:/testtask"
     - "./build/php-fpm/php.ini:/etc/php/7.3/fpm/php.ini:ro"
     - "./volumes/data:/opt/data"
    ports:
     - "127.0.0.1:9009:9000"
    environment:
      XDEBUG_CONFIG: >
        idekey=PHPSTORM
        remote_enable=1
        remote_host=172.22.0.1
        remote_port=9000
        profiler_enable=0
        coverage_enable=0
    networks:
     - testtask_swarm

  redis:
    image: redis:3.0
    hostname: redis
    ports:
     - "127.0.0.1:6379:6379"
    networks:
     - testtask_swarm

networks:
  testtask_swarm:
    external: true
